name: "Mu dApp - Deploy"

on:
  push:
    branches:
      - staging

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Deploy to IPFS & Crust
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node Modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('*/*/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          export SKIP_POSTINSTALL=1 
          yarn install
          cd ./packages/hardhat
          yarn install 
          yarn postdeploy --network celo-alfajores
          cd ../react-app 
          yarn install

      - name: Build
        env:
          REACT_APP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/resource-network/resource_testnet
          REACT_APP_RESOURCE_URL: https://staging-api.resourcenetwork.co/graphql
          REACT_APP_NETWORK_NAME: celo-alfajores
        run: |
          cd ./packages/react-app/
          export CI=false 
          yarn codegen
          yarn build

      - name: Upload to IPFS & pin via Pinata
        id: upload
        uses: ReSource-Network/ipfs-action@v1.8.1
        with:
          path: ./packages/react-app/build
          pinataPinName: source-dapp
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}

      - name: Update DNSLink
        id: dnslink
        uses: ReSource-Network/cloudlfare-dnslink-update@v1.21
        with:
          CID: ${{ steps.upload.outputs.hash }}
          TOKEN: ${{secrets.CLOUDFLARE_TOKEN}}
          ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
          RECORD_DOMAIN: "resource.finance"
          RECORD_NAME: "_dnslink.staging"
